{% set name = "aws-c-event-stream" %}
{% set version = "0.5.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awslabs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: e94a8172e7d198d11bc7aa769c5334f1a8518f2b5bd4446d37d18fb5683623fd

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("aws-c-event-stream", max_pin="x.x.x") }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - cmake >=3.9
    - ninja-base
  host:
    - aws-c-common 0.12.4
    - aws-checksums 0.2.7
    - aws-c-io 0.21.4

test:
  commands:
    - test -f $PREFIX/lib/libaws-c-event-stream${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/aws/event-stream/event_stream.h  # [unix]
    - if not exist %LIBRARY_BIN%\aws-c-event-stream.dll exit 1  # [win]
    - if not exist %LIBRARY_INC%\aws\event-stream\event_stream.h exit 1  # [win]

about:
  home: https://github.com/awslabs/aws-c-event-stream
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: C99 implementation of the vnd.amazon.eventstream content-type.
  description: C99 implementation of the vnd.amazon.eventstream content-type.
  doc_url: https://github.com/awslabs/aws-c-event-stream
  dev_url: https://github.com/awslabs/aws-c-event-stream

extra:
  recipe-maintainers:
    - xhochy
