{% set name = "aws-c-event-stream" %}
{% set version = "0.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awslabs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f6e55c8fd6afd7f904e08d36c3210e199ece5dc838f0f8457b43b72ec4d818e9

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("aws-c-event-stream", max_pin="x.x.x") }}

requirements:
  build:
    - cmake >=3.9
    - {{ compiler('c') }}
    - ninja-base
  host:
    - aws-c-common 0.12.3
    - aws-checksums 0.2.7
    - aws-c-io 0.20.1

test:
  commands:
    - test -f $PREFIX/lib/libaws-c-event-stream${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/aws/event-stream/event_stream.h  # [unix]
    - if not exist %PREFIX%\\Library\\bin\\aws-c-event-stream.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\include\\aws\\event-stream\\event_stream.h exit 1  # [win]

about:
  home: https://github.com/awslabs/aws-c-event-stream
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: C99 implementation of the vnd.amazon.eventstream content-type.
  description: C99 implementation of the vnd.amazon.eventstream content-type.
  doc_url: https://github.com/awslabs/aws-c-event-stream
  dev_url: https://github.com/awslabs/aws-c-event-stream

extra:
  recipe-maintainers:
    - xhochy
