{% set name = "aws-c-event-stream" %}
{% set version = "0.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awslabs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: cef8b78e362836d15514110fb43a0a0c7a86b0a210d5fe25fd248a82027a7272

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("aws-c-event-stream", max_pin="x.x.x") }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja-base
  host:
    - aws-c-common 0.11.1
    - aws-checksums 0.2.3
    - aws-c-io 0.17.0
  run:
    - aws-c-common # pinning by run_exports
    - aws-checksums # pinning by run_exports
    - aws-c-io # pinning by run_exports

test:
  commands:
    - test -f $PREFIX/lib/libaws-c-event-stream${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/aws/event-stream/event_stream.h  # [unix]

about:
  home: https://github.com/awslabs/aws-c-event-stream
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: C99 implementation of the vnd.amazon.eventstream content-type.
  description: C99 implementation of the vnd.amazon.eventstream content-type.
  doc_url: https://github.com/awslabs/aws-c-event-stream
  dev_url: https://github.com/awslabs/aws-c-event-stream

extra:
  skip-lints:
    - missing_tests
  recipe-maintainers:
    - xhochy
