{% set name = "aws-c-event-stream" %}
{% set version = "0.2.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awslabs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 4ff2ada07ede3c6afa4b8e6e20de541e717038307f29b38c27efa7c4d875ee26

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("aws-c-event-stream", max_pin="x.x.x") }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja
  host:
    - aws-c-common 0.8.5
    - aws-checksums 0.1.13
  run:
    - aws-c-common >=0.8.5,<0.8.6.0a0
    - aws-checksums >=0.1.13,<0.1.14.0a0

test:
  commands:
    - test -f $PREFIX/lib/libaws-c-event-stream${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/aws/event-stream/event_stream.h  # [unix]

about:
  home: https://github.com/awslabs/aws-c-event-stream
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: C99 implementation of the vnd.amazon.eventstream content-type.
  description: C99 implementation of the vnd.amazon.eventstream content-type.
  doc_url: https://github.com/awslabs/aws-c-event-stream
  dev_url: https://github.com/awslabs/aws-c-event-stream

extra:
  skip-lints:
    - missing_tests
  recipe-maintainers:
    - xhochy
