{% set name = "aws-c-event-stream" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awslabs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 7d4e2f1df43a1198ed4d95870ac10eb9fba517ab0aac988e6f940aaa61052a9a

build:
  number: 6
  run_exports:
    - {{ pin_subpackage("aws-c-event-stream", max_pin="x.x.x") }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja
  host:
    - aws-c-common 0.6.8
    - aws-checksums 0.1.11
  run:
    - aws-c-common >=0.6.8,<0.6.9.0a0
    - aws-checksums >=0.1.11,<0.1.12.0a0

test:
  commands:
    - test -f $PREFIX/lib/libaws-c-event-stream${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/aws/event-stream/event_stream.h  # [unix]

about:
  home: https://github.com/awslabs/aws-c-event-stream
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: C99 implementation of the vnd.amazon.eventstream content-type.
  description: C99 implementation of the vnd.amazon.eventstream content-type.
  doc_url: https://github.com/awslabs/aws-c-event-stream
  dev_url: https://github.com/awslabs/aws-c-event-stream

extra:
  skip-lints:
    - missing_tests
  recipe-maintainers:
    - xhochy
